scrape_configs:

  - job_name: 'User Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['172.24.224.1:9010']
        labels:
          application: 'User Service Microservice'
