version: "3.9"

services:

  mongo-command-service:
    image: mongo
    container_name: mtc-mongo-command-service
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mtc
      MONGO_INITDB_ROOT_PASSWORD: mtc
    networks:
      - mtc

  mongo-command-express:
    image: mongo-express
    container_name: mtc-mongo-command-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mtc
      ME_CONFIG_MONGODB_ADMINPASSWORD: mtc
      ME_CONFIG_MONGODB_URL: mongodb://mtc:mtc@mongo-command-service:27017
    networks:
      - mtc

  mongo-query-service:
    image: mongo
    container_name: mtc-mongo-query-service
    ports:
      - 27018:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mtc
      MONGO_INITDB_ROOT_PASSWORD: mtc
    networks:
      - mtc

  mongo-query-express:
    image: mongo-express
    container_name: mtc-mongo-query-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mtc
      ME_CONFIG_MONGODB_ADMINPASSWORD: mtc
      ME_CONFIG_MONGODB_URL: mongodb://mtc:mtc@mongo-query-service:27017
    networks:
      - mtc

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: mtc-kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mtc

  broker:
    image: confluentinc/cp-kafka
    container_name: mtc-kafka-broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_REPLICATION_FACTOR: 1
    networks:
      - mtc

networks:
  mtc:
    name: mtc-network